[package]
name = "vk-ml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37"
bytemuck = { version = "1.14", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
